title: "MyAlpha"
description: "Professional consulting and architecture"
remote_theme: "mmistakes/minimal-mistakes"
url: "https://devmanager2.github.io"
baseurl: "/myalpha.github.io"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
